services:
  laneh-app:
    image: docker.io/hildedev/laneh:latest
    restart: always
    ports:
      - 127.0.0.1:${APP_PORT}:3000
    env_file:
      - .env
    environment:
      DOCKER_DATABASE_LOCATION: /data/pglite
      NODE_ENV: production
    volumes:
      - ${DATABASE_LOCATION}:/data/pglite
    networks:
      - laneh-network

networks:
  laneh-network:
    driver: bridge
